<div class="row mx-auto p-0 textoVerde1 mb-5">
    <div class="contenedor bgBlanco">
        <div class="row">
            <h2>Observaciones</h2>
        </div>

        <form class="row text-end">
            <div class="row texto-justificado">
                <span class="mb-3" contenteditable="true">Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet, dolor iusto. Autem doloribus modi quia non consequatur obcaecati facilis laborum porro aut? Harum, magnam vero aliquid tenetur assumenda eveniet rerum nisi facere fuga perspiciatis dolores voluptas temporibus, distinctio dolore, ducimus vitae ea atque error pariatur. Illum aliquam aperiam maxime soluta quas provident! Pariatur unde eum provident cupiditate debitis temporibus ipsam necessitatibus harum voluptates. Mollitia fugit libero deserunt dolore et nobis distinctio voluptatem id consectetur. Culpa nemo, deserunt beatae assumenda, ipsa ex repellendus labore non laborum eos ab ipsum illum distinctio eaque ut voluptates, ratione recusandae quod alias vel explicabo repellat molestias repudiandae? Illum, impedit distinctio, reprehenderit nesciunt esse ipsam architecto aspernatur veniam sint cum animi, dolorum magnam. Nostrum ex sequi labore. Nam iste, velit enim mollitia fugit sint harum voluptates doloribus excepturi animi corporis nostrum culpa ipsum doloremque commodi hic pariatur atque. Assumenda, nemo molestias eaque odit, soluta hic maxime, saepe illo rem quibusdam natus? Iste repellendus veritatis voluptates sint molestias commodi ut quos amet tenetur. Cupiditate voluptatibus, ipsam natus impedit nemo dolores quasi laboriosam delectus sequi atque dignissimos voluptates facilis, deserunt sapiente adipisci. Voluptatibus quos tenetur ex magni. Dolor, aut. Velit fugit exercitationem laborum odio rem blanditiis sit quidem explicabo maxime, soluta sapiente tempora officiis iusto voluptatibus. Quo laborum suscipit, doloremque omnis eius autem laboriosam incidunt eos, nesciunt corrupti facilis odit harum, quis sed officiis expedita delectus dolor id totam. Eius ex, similique, voluptate id ut quaerat in nesciunt modi tempore obcaecati facere. Ipsa iste deleniti perspiciatis error fuga. Ea eveniet tempora dolores laudantium perferendis, nesciunt impedit tempore molestias odit commodi vel! Amet, tempore quas suscipit, minima dolor fugit soluta sunt pariatur inventore tenetur magni! Ducimus, quia error consequuntur illo inventore, quae dolore deleniti nobis non iusto porro perferendis vero numquam. Quam, nihil aspernatur accusamus deserunt voluptas velit labore consequuntur maxime illum cupiditate et architecto commodi odit rem reiciendis. Delectus in voluptas accusamus! Dolore tenetur deserunt fugiat optio soluta placeat beatae accusamus?</span>
            </div>
            <input type="button" name="Guardar" value="Guardar">
        </form>
    </div>
</div>
